AEOnline/AEOnline/Models/WebModels/GraficosCombustible.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AEOnline.Models.WebModels
{
    public class GraficosCombustible
    {
        public int Year { get; set; }
        public List<HistorialCargaCombustible> Historiales { get; set; }
        public List<Proveedor> Proveedores { get; set; }
        public List<Operador> Operadores { get; set; }
        public List<Auto> Vehiculos { get; set; }

    }
}

AEOnline/AEOnline/Controllers/web/AdminFlota2Controller.cs
using AEOnline.ClasesAdicionales;
using AEOnline.Models;
using AEOnline.Models.WebModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using static AEOnline.Controllers.web.UserNormalController;

namespace AEOnline.Controllers.web
{
    public class AdminFlota2Controller : Controller
    {
        private ProyectoAutoContext db = new ProyectoAutoContext();

        // GET: AdminFlota
        public ActionResult Index()
        {
            if (Session["Flota"] == null)
                return RedirectToAction("SinFlota");

            int idFlota = (int)Session["Flota"];
            Flota flota = db.Flotas.Where(f => f.Id == idFlota).FirstOrDefault();

            List<Auto> autos = flota.Autos.Where(a => a.Atajo == true).ToList();

            AtajosPanelInicial atajos = new AtajosPanelInicial();
            atajos.Autos = autos;

            return View(atajos);
        }

        public ActionResult MapaDeFlota()
        {
            if (Session["Email"] == null)
                return RedirectToAction("Index", "Login");
            if (Session["Flota"] == null)
                return RedirectToAction("SinFlota");

            int idFlota = (int)Session["Flota"];
            Flota flota = db.Flotas.Where(f => f.Id == idFlota).FirstOrDefault();

            return View(flota);
        }

        public ActionResult MisVehiculos()
        {
            return View();
        }



        #region ----------------------ADMIN VEHICULOS ------------------------------------------

        public ActionResult AdministrarAutos()
        {
            if (Session["Email"] == null)
                return RedirectToAction("Index", "Login");
            if (Session["Flota"] == null)
                return RedirectToAction("SinFlota");

            int idFlota = (int)Session["Flota"];
            Flota flota = db.Flotas.Where(f => f.Id == idFlota).FirstOrDefault();

            List<Auto> autos = flota.Autos.ToList();

            return View(autos);
        }

        public ActionResult CrearAuto()
        {
            if (Session["Flota"] == null)
                return RedirectToAction("SinFlota");

            int idFlota = (int)Session["Flota"];
            Flota flota = db.Flotas.Where(f => f.Id == idFlota).FirstOrDefault();

            //List<Operador> operadoresSinAuto = flota.Operadores.Where(o => o.Auto == null).ToList();
            List<Operador> operadoresSinAuto = flota.Operadores.Where(o => o.Autos.Count == 0).ToList();
            operadoresSinAuto.Add(new Operador() { Id = 0, Nombre = "No asignar" });
            operadoresSinAuto.Reverse();

            List<TipoVehiculo> tipoVehiculos = flota.TiposVehiculo.ToList();
            tipoVehiculos.Add(new TipoVehiculo() { Id = 0, Tipo = "No asignar" });
            tipoVehiculos.Reverse();

            ViewBag.OperadorId = new SelectList(operadoresSinAuto, "Id", "Nombre");
            ViewBag.TipoVehiculoId = new SelectList(tipoVehiculos, "Id", "Tipo");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearAuto([Bind(Include = "Id,NombreVehiculo,Patente,Marca,Modelo,Year,KilometrajeActual,TipoVehiculoId,OperadorId")] CreacionAuto model)
        {
            if (Session["Flota"] == null)
                return RedirectToAction("SinFlota");

            int idFlota = (int)Session["Flota"];
            Flota flota = db.Flotas.Where(f => f.Id == idFlota).FirstOrDefault();

            if(flota.PackId != null)
            {
                if(flota.Autos.Count >= flota.PackServicio.NumeroVehiculos)
                {
                    TempData["msg"] = "No puede superar el número máximo de vehículos. Su pack de servicios tiene un límite de "+flota.PackServicio.NumeroVehiculos;
                    return RedirectToAction("AdministrarAutos");
                }
            }

            Auto repetido = flota.Autos.Where(a => a.NombreVehiculo == model.NombreVehiculo).FirstOrDefault();
            if (repetido != null)
            {
                ModelState.Clear();
                ModelState.AddModelError("NombreVehiculo", "Ya existe un vehículo en su flota con el mismo nombre.");
                TryValidateModel(model);
            }


            if (ModelState.IsValid == false)
            {
                List<Operador> operadoresSinAuto = flota.Operadores.Where(o => o.Autos.Count == 0).ToList();
                //List<Operador> operadoresSinAuto = flota.Operadores.Where(o => o.Auto == null).ToList();
                operadoresSinAuto.Add(new Operador() { Id = 0, Nombre = "No asignar" });
                operadoresSinAuto.Reverse();

                List<TipoVehiculo> tipoVehiculos = flota.TiposVehiculo.ToList();
                tipoVehiculos.Add(new TipoVehiculo() { Id = 0, Tipo = "No asignar" });
                tipoVehiculos.Reverse();

                ViewBag.OperadorId = new SelectList(operadoresSinAuto, "Id", "Nombre");
                ViewBag.TipoVehiculoId = new SelectList(tipoVehiculos, "Id", "Tipo");

                return View("CrearAuto", model);
            }


            TipoVehiculo tipo = flota.TiposVehiculo.Where(t => t.Id == model.TipoVehiculoId).FirstOrDefault();
            Auto.CrearAuto(db, model.NombreVehiculo, model.Patente, tipo, model.Marca, model.Modelo, model.Year, model.KilometrajeActual, idFlota, model.OperadorId);

            TempData["msg"] = "Vehículo creado correctamente";
            return RedirectToAction("AdministrarAutos");
        }


        public ActionResult EditarAuto(int? id)
        {
            if (Session["Flota"] == null)
                return RedirectToAction("SinFlota");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Auto auto = db.Autos.Find(id);

            if (auto == null)
            {
                return HttpNotFound();
            }

            int idFlota = (int)Session["Flota"];
            Flota flota = db.Flotas.Where(f => f.Id == idFlota).FirstOrDefault();

            CreacionAuto modeloAuto = new CreacionAuto()
            {
                Id = auto.Id,
                NombreVehiculo = auto.NombreVehiculo,
                Patente = auto.Patente,
                Marca = auto.Marca,
                Modelo = auto.Modelo,
                Year = auto.Year,
                KilometrajeActual = auto.KilometrajeActual,
                FlotaId = idFlota,
                OperadorId = 0,
                TipoVehiculoId = 0
            };


            //List<Operador> operadoresSinAuto = flota.Operadores.Where(o => o.Auto == null).ToList();
            List<Operador> operadoresSinAuto = flota.Operadores.Where(o => o.Autos.Count == 0).ToList();
            if (auto.OperadorId != null)
            {
                modeloAuto.OperadorId = auto.Operador.Id;
                Operador operadorActual = flota.Operadores.Where(o => o.Id == auto.Operador.Id).FirstOrDefault();
                operadoresSinAuto.Add(operadorActual);
            }
            operadoresSinAuto.Add(new Operador() { Id = 0, Nombre = "No asignar" });
            operadoresSinAuto.Reverse();

            List<TipoVehiculo> tipoVehiculos = flota.TiposVehiculo.ToList();
            if (auto.TipoVehiculo != null)
                modeloAuto.TipoVehiculoId = auto.TipoVehiculo.Id;
            tipoVehiculos.Add(new TipoVehiculo() { Id = 0, Tipo = "No asignar" });
            tipoVehiculos.Reverse();

            ViewBag.OperadorId = new SelectList(operadoresSinAuto, "Id", "Nombre", modeloAuto.OperadorId);
            ViewBag.TipoVehiculoId = new SelectList(tipoVehiculos, "Id", "Tipo", modeloAuto.TipoVehiculoId);

            return View(modeloAuto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarAuto([Bind(Include = "Id,NombreVehiculo,Patente,Marca,Modelo,Year,KilometrajeActual,TipoVehiculoId,OperadorId")] CreacionAuto model)
        {
            if (Session["Flota"] == null)
                return RedirectToAction("SinFlota");

            int idFlota = (int)Session["Flota"];
            Flota flota = db.Flotas.Where(f => f.Id == idFlota).FirstOrDefault();
            Auto auto = flota.Autos.Where(a => a.Id == model.Id).FirstOrDefault();

            Auto repetido = flota.Autos.Where(a => a.NombreVehiculo == model.NombreVehiculo && a.Id != auto.Id).FirstOrDefault();
            if (repetido != null)
            {
                ModelState.Clear();
                ModelState.AddModelError("NombreVehiculo", "Ya existe un vehículo en su flota con el mismo nombre.");
                TryValidateModel(model);
            }

            if (ModelState.IsValid == false)
            {

                List<Operador> operadoresSinAuto = flota.Operadores.Where(o => o.Autos.Count == 0).ToList();
                //List<Operador> operadoresSinAuto = flota.Operadores.Where(o => o.Auto == null).ToList();
                operadoresSinAuto.Add(new Operador() { Id = 0, Nombre = "No asignar" });
                operadoresSinAuto.Reverse();

                List<TipoVehiculo> tipoVehiculos = flota.TiposVehiculo.ToList();
                tipoVehiculos.Add(new TipoVehiculo() { Id = 0, Tipo = "No asignar" });
                tipoVehiculos.Reverse();

                int operadorSeleccionado = 0;
                int tipoVehiculoSeleccionado = 0;

                if (auto.OperadorId != null)
                    operadorSeleccionado = auto.Operador.Id;
                if (auto.TipoVehiculo != null)
                    tipoVehiculoSeleccionado = auto.TipoVehiculo.Id;

                ViewBag.OperadorId = new SelectList(operadoresSinAuto, "Id", "Nombre", operadorSeleccionado);
                ViewBag.TipoVehiculoId = new SelectList(tipoVehiculos, "Id", "Tipo", tipoVehiculoSeleccionado);

AEOnline/AEOnline/Views/AdminFlota2/AdministrarAutos.cshtml
@model IEnumerable<AEOnline.Models.Auto>
@{
    ViewBag.Title = "AdministrarAutos";

    Layout = "~/Views/Shared/_LayoutAdminFlota2.cshtml";

    string rol = "";

    if (Session["Rol"] != null)
    {
        rol += Session["Rol"].ToString();
    }

    if (rol != "AdminDeFlota")
    {
        Response.Redirect("~/Login/Index");
    }
}

<div class="container m-lg-1">
    <div class="btn-group m-lg-1">
        <a href="@Url.Action("CrearAuto","AdminFlota2")" class="btn btn-primary">
            <i class="fa fa-fw fa-plus"></i>
            Registrar nuevo auto
        </a>
    </div>
    @*<div class="btn-group float-right m-lg-1">
        <a href="@Url.Action("HistorialesCombustible","AdminFlota2")" class="btn btn-primary">
            <i class="fa fa-fw fa-tint"></i>
            Historiales combustible
        </a>
    </div>*@
</div>

<div class="card mb-3">
    <div class="card-header" id="cuadroMensaje">
        <div class="alert alert-success" role="alert">
            <h4 id="lblMensaje">@TempData["msg"]</h4>
        </div>

        <i class="fa fa-table"></i><strong><font size="5"> Vehículos</font></strong>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
         
                            @Html.DisplayNameFor(model => model.NombreVehiculo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Patente)
                        </th>
                        <th>
                            Tipo de vehículo
                        </th>
                        <th>
                            Operador
                        </th>
                        <th>
                            Kilometraje actual
                        </th>
                        <th>
                            Acceso en panel Inicio
                        </th>
                        <th>
                            Registros móviles
                        </th>
                        <th>
                            <p>Acciones</p>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <div class="btn-group m-lg-1">
                                    <a href="@Url.Action("FichaAuto", "AdminFlota2", new { id = item.Id , menu = 0})" class="btn btn-success">
                                        <i class="fa fa-fw fa-car"></i>
                                        @Html.DisplayFor(modelItem => item.NombreVehiculo)
                                    </a>
                                </div>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Patente)
                            </td>
                            <td>
                                @{
                                    string tipo = "-";
                                    if (item.TipoVehiculo != null)
                                    {
                                        tipo = item.TipoVehiculo.Tipo;
                                    }
                                }
                                @tipo
                            </td>
                            <td>
                                @{
                                    string nOperador = "-";

                                    if (item.OperadorId != null)
                                    {
                                        nOperador = item.Operador.Nombre;
                                    }
                                }
                                @nOperador
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.KilometrajeActual)
                            </td>
                            <td>
                                @Html.CheckBoxFor(modelItem => item.Atajo,  new { onclick = "checkBoxClick("+item.Id+")" })
                            </td>
                            <td>
                                <div class="btn-group m-lg-1">
                                    <a href="@Url.Action("RegistrosCelular", "AdminFlota2", new { id = item.Id , tipo = 1})" class="btn btn-info">
                                        <i class="fa fa-fw fa-bar-chart"></i>
                                        Registros
                                    </a>
                                </div>
                            </td>
                            <td align="center">
                                <ul class="navbar-nav ml-lg-1">
                                    <li  class="nav-item dropdown">
                                        <a class="dropdown-toggle mr-lg-2" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-fw fa-cog"></i>
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                                            <a class="dropdown-item" href="@Url.Action("CargarCombustible", "AdminFlota2", new { id = item.Id })">
                                                <div class="dropdown-message small"><i class="fa fa-fw fa-tint"></i>Cargar combustible</div>
                                            </a>
                                            <a class="dropdown-item" href="@Url.Action("EditarAuto","AdminFlota2", new { id = item.Id})">
                                                <div class="dropdown-message small"><i class="fa fa-fw fa-edit"></i> Editar</div>
                                            </a>
                                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#borrarModal" 
                                               data-id="@item.Id" data-name="@item.NombreVehiculo">
                                                <div class="dropdown-message small"><i class="fa fa-fw fa-trash-o"></i>Eliminar</div>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


	
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}

<!-- Delete Modal-->
<div class="modal fade" id="borrarModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">TITULO</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Se borrará el vehículo y todos sus historiales asociados. No habrá forma de recuperar la información después de presionar en "Aceptar".</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary btn-ok" href="#" data-dismiss="modal">Aceptar</a>
            </div>
        </div>
    </div>
</div>

@section scripts{
<script>

    $mensaje = $('#lblMensaje');

    document.getElementById("cuadroMensaje").style.display = "none";

    if ($mensaje.text() != "")
    {
        document.getElementById("cuadroMensaje").style.display = "block";
    }

    //e  es el elemnto que hace aparecer el modal
    //la informacion se le agrega en data-id y hay oportunidad de agregar mas como data-name, etc
    //esa informacion se le asigna al btn ok del modal
    $('#borrarModal').on('show.bs.modal', function (e) {
        var data = $(e.relatedTarget).data();
        $('.modal-title', this).text("¿Está seguro que desea borrar el vehículo '"+data.name+"'?");
        $('.btn-ok', this).data('recordId', data.id);
    });


    //El boton modal cuando es clickeado lee la informacion que se le fue asignada anteriormente
    //luego forma la url correcta y envia en modo post
    $('#borrarModal').on('click', '.btn-ok', function (e) {
        var $modalDiv = $(e.delegateTarget);
        var $id = $(this).data('recordId');
        var form = $('#__AjaxAntiForgeryForm');
        var token = $('input[name="__RequestVerificationToken"]', form).val();

        $.ajax({
            type: "POST",
            url: "/AdminFlota2/EliminarAuto",
            data: {
                __RequestVerificationToken: token,
                id: $id
            },
            success: function (result) {
                location.reload(true);
            },
            error: function (response) {
                //debugger;
                alert('eror');
            }
        });
    });


    function checkBoxClick(idAuto)
    {
        var form = $('#__AjaxAntiForgeryForm');
        var token = $('input[name="__RequestVerificationToken"]', form).val();

        $.ajax({
            type: "POST",
            url: "/AdminFlota2/CambiarAtajoAuto",
            data: {
                __RequestVerificationToken: token,
                AutoId: idAuto
            },
            success: function (result) {
                //location.reload(true);
            },
            error: function (response) {
                //debugger;
                alert('eror');
            }
        });
    }


</script>
}

AEOnline/AEOnline/Views/AdminFlota2/AdministrarOperadores.cshtml
@model IEnumerable<AEOnline.Models.Operador>

@{
    ViewBag.Title = "AdministrarOperadores";

    Layout = "~/Views/Shared/_LayoutAdminFlota2.cshtml";

    string rol = "";

    if (Session["Rol"] != null)
    {
        rol += Session["Rol"].ToString();
    }

    if (rol != "AdminDeFlota")
    {
        Response.Redirect("~/Login/Index");
    }
}

<div class="container m-lg-1">
    <div class="btn-group m-lg-1">
        <a href="@Url.Action("CrearOperador","AdminFlota2")" class="btn btn-primary">
            <i class="fa fa-fw fa-plus"></i>
            Crear nuevo operador
        </a>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header">
        <div class="alert alert-success" role="alert">
            <h4 id="lblMensaje">@TempData["msg"]</h4>
        </div>
        <i class="fa fa-table"></i> <strong><font size="5"> Operadores de la flota</font></strong>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            Usuario
                        </th>
                        <th>
                            Auto
                        </th>
                        <th>
                            Tipo de licencia
                        </th>
                        <th>
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @{
                                    string user = "-";

                                    if (item.Usuario != null)
                                    {
                                        user = item.Usuario.Email;
                                    }
                                }
                                @user
                            </td>
                            <td>
                                @{
                                    string auto = "-";

                                    //if (item.Auto != null)
                                    //{
                                    //    auto = item.Auto.NombreVehiculo;
                                    //}
                                    if(item.Autos.Count > 0)
                                    {
                                        auto = item.Autos.First().NombreVehiculo;
                                    }
                                }
                                @auto
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TipoLicencia)
                            </td>
                            <td align="center">
                                <ul class="navbar-nav ml-lg-1">
                                    <li class="nav-item dropdown">
                                        <a class="dropdown-toggle mr-lg-2" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-fw fa-cog"></i>
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                                            <a class="dropdown-item" href="@Url.Action("EditarOperador","AdminFlota2", new { id = item.Id})">
                                                <div class="dropdown-message small"><i class="fa fa-fw fa-edit"></i> Editar</div>
                                            </a>
                                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#borrarModal"
                                               data-id="@item.Id" data-name="@item.Nombre">
                                                <div class="dropdown-message small"><i class="fa fa-fw fa-trash-o"></i>Eliminar</div>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                     }
                </tbody>
            </table>
        </div>
    </div>
</div>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}

<!-- Delete Modal-->
<div class="modal fade" id="borrarModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">TITULO</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Al apretar "Aceptar" se borrara este operador y la unión que mantenia entre su respectivo auto y usuario.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-primary btn-ok" href="#" data-dismiss="modal">Aceptar</a>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>


    //e  es el elemnto que hace aparecer el modal
    //la informacion se le agrega en data-id y hay oportunidad de agregar mas como data-name, etc
    //esa informacion se le asigna al btn ok del modal
    $('#borrarModal').on('show.bs.modal', function (e) {
        var data = $(e.relatedTarget).data();
        $('.modal-title', this).text("¿Está seguro que desea borrar el operador '"+data.name+"'?");
        $('.btn-ok', this).data('recordId', data.id);
    });


    //El boton modal cuando es clickeado lee la informacion que se le fue asignada anteriormente
    //luego forma la url correcta y envia en modo post
    $('#borrarModal').on('click', '.btn-ok', function (e) {
        var $modalDiv = $(e.delegateTarget);
        var $id = $(this).data('recordId');
        var form = $('#__AjaxAntiForgeryForm');
        var token = $('input[name="__RequestVerificationToken"]', form).val();

        $.ajax({
            type: "POST",
            url: "/AdminFlota2/EliminarOperador",
            data: {
                __RequestVerificationToken: token,
                id: $id
            },
            success: function (result) {
                location.reload(true);
            },
            error: function (response) {
                //debugger;
                alert('eror');
            }
        });
    });



    </script>
}

AEOnline/AEOnline/Views/AdminFlota2/CrearOperador.cshtml
@model AEOnline.Models.WebModels.CreacionOperador

@{
    ViewBag.Title = "AgregarOperador";

    Layout = "~/Views/Shared/_LayoutAdminFlota2.cshtml";

    string rol = "";

    if (Session["Rol"] != null)
    {
        rol += Session["Rol"].ToString();
    }

    if (rol != "AdminDeFlota")
    {
        Response.Redirect("~/Login/Index");
    }
}

<body class="bg-dark">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="container">
            <div class="card card-register mx-auto mt-5">
                <div class="card-header">Crear nuevo Operador</div>
                <div class="card-body">
                    <form>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-6">
                                    <p>Nombre</p>
                                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-6">
                                    <p>Tipo de licencia</p>
                                    @Html.EditorFor(model => model.TipoLicencia, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TipoLicencia, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-6">
                                    <p>Usuario asignado</p>
                                   @Html.DropDownList("UsuarioId", null, htmlAttributes: new { @class = "form-control", @id = "cmbUsuario" })
                                </div>
                                <div class="col-md-6">
                                    <p>Auto asignado</p>
                                    @Html.DropDownList("AutoId", null, htmlAttributes: new { @class = "form-control", @id = "cmbAuto" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Crear nuevo operador" class="btn btn-primary btn-block" />
                        </div>
                    </form>
                    <div class="text-center">
                        <a class="d-block small mt-3" href="@Url.Action("AdministrarOperadores","AdminFlota2")"><< Regresar a la lista</a>
                    </div>
                </div>
            </div>
        </div>
    }

</body>


@section Scripts {

@* Referencias Chosen *@
@*<link href="~/Content/Chosen/chosen.min.css" rel="stylesheet" />
<script src="~/Scripts/chosen.jquery.min.js"></script>
    <script>
        $(function () {
            $("#cmbUsuario").chosen();

        });
    </script>*@
}